class Hive < Formula
  desc "Folder-as-agent pipeline for autonomous software tasks"
  homepage "https://github.com/ivankuznetsov/hive"
  url "https://github.com/ivankuznetsov/hive/releases/download/v0.1.2/hive-cli-0.1.2.gem"
  version "0.1.2"
  sha256 "280d9d176f67b08fe12c019645167587fe78ff62ef89f49d8889c094e0ed721b"
  license "MIT"

  depends_on "ruby"

  def install
    # Vendor hive-cli and its runtime deps into the formula's libexec
    # so they never collide with the user's default gem environment.
    # The Ruby formula pattern: gem install -i <prefix>, then write a
    # wrapper that exports GEM_HOME/GEM_PATH and execs the real bin.
    ENV["GEM_HOME"] = libexec.to_s
    system "gem", "install", cached_download,
           "--install-dir", libexec,
           "--no-document",
           "--bindir", libexec/"bin"
    (libexec/"share/hive").mkpath
    (libexec/"share/hive/install-channel").write "brew\n"

    # Symlink user-facing bins through libexec wrappers so GEM_PATH
    # is set when hive resolves bubbletea, lipgloss, etc.
    %w[hive hv].each do |name|
      (bin/name).write <<~SH
        #!/bin/bash
        export GEM_HOME="#{libexec}"
        export GEM_PATH="${GEM_HOME}${GEM_PATH:+:$GEM_PATH}"
        export HIVE_INVOKED_BIN="${HIVE_INVOKED_BIN:-$0}"
        exec "#{libexec}/bin/#{name}" "$@"
      SH
      (bin/name).chmod 0755
    end
  end

  def caveats
    <<~EOS
      Run `hive daemon install` once to install and load the per-user daemon
      service, then run `hive init` inside a project to scaffold .hive-state
      and choose whether that project is enrolled for daemon dispatch. If
      Apache Hive shadows this binary on PATH, use `hv`.

      Homebrew launchd units generated by `hive daemon install` point at the
      stable Homebrew bin/hive symlink, so `brew upgrade hive` keeps the daemon
      path current. If you previously customized the plist, remove it and re-run
      `hive daemon install --force` to install the current template.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hive --version")
  end
end
