class Hive < Formula
  desc "Folder-as-agent pipeline for autonomous software tasks"
  homepage "https://github.com/ivankuznetsov/hive"
  url "https://github.com/ivankuznetsov/hive/releases/download/v0.7.0/hive-cli-0.7.0.gem"
  version "0.7.0"
  sha256 "758af399660112bf267f8bf050345f2f96690f316d5e24bf64bd9a6c73c95d64"
  license "MIT"

  depends_on "ruby"
  depends_on "cosign"

  def install
    # Vendor hive-cli and its runtime deps into the formula's libexec
    # so they never collide with the user's default gem environment.
    # The Ruby formula pattern: gem install -i <prefix>, then write a
    # wrapper that exports GEM_HOME/GEM_PATH and execs the real bin.
    ENV["GEM_HOME"] = libexec.to_s
    system "gem", "install", cached_download,
           "--install-dir", libexec,
           "--no-document",
           "--bindir", libexec/"bin"
    # Marker under <prefix>/share (linked into the Homebrew prefix), NOT
    # libexec/share — libexec is private and never linked, so a marker
    # there is invisible to Hive::InstallChannel, which probes
    # <prefix>/share/hive/install-channel.
    (share/"hive").mkpath
    (share/"hive/install-channel").write "brew\n"

    # User-facing bin/hive wrapper that exports GEM_HOME/GEM_PATH before
    # exec'ing the gem-installed hive so it resolves bubbletea, lipgloss, etc.
    (bin/"hive").write <<~SH
      #!/bin/bash
      export GEM_HOME="#{libexec}"
      export GEM_PATH="${GEM_HOME}${GEM_PATH:+:$GEM_PATH}"
      export HIVE_INVOKED_BIN="${HIVE_INVOKED_BIN:-$0}"
      exec "#{libexec}/bin/hive" "$@"
    SH
    (bin/"hive").chmod 0755

    # hv is a symlink to the hive wrapper, NOT the gem's bin/hv: bin/hv is
    # a bash script and `gem install` wraps every executable in a Ruby
    # binstub that cannot run it. The symlink gives a working Apache-Hive
    # collision shim that runs our hive.
    bin.install_symlink "hive" => "hv"
  end

  def caveats
    <<~EOS
      Run `hive setup` inside a project to bootstrap Hive web, install and load
      the per-user web and daemon services, and enroll the project. The default
      URL is loopback-only; use `hive setup --no-service` to keep Hive web
      foreground-only. If Apache Hive shadows this binary on PATH, use `hv`.

      Homebrew launchd units generated by `hive setup` point at the
      stable Homebrew bin/hive symlink, so `brew upgrade hive` keeps the daemon
      path current. If you previously customized the plist, remove it and re-run
      `hive daemon install --force` to install the current template.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hive --version")
  end
end
